### ISSUE TITLE
win10 run problem

### ISSUE THREAD

**Issue by ozkanpakdil** [ozkanpakdil/swaggerific#3]
```
[Tue May 23 07:40:29 BST 2023][INFO] [SUB] Main
[Tue May 23 07:40:29 BST 2023][INFO] [SUB] May 23, 2023 7:40:29 AM com.sun.javafx.application.PlatformImpl startup
[Tue May 23 07:40:29 BST 2023][INFO] [SUB] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @e48b597'
[Tue May 23 07:40:30 BST 2023][INFO] [SUB] Exception in Application start method
[Tue May 23 07:40:30 BST 2023][INFO] [SUB] Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:893)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at java.lang.Thread.run(Thread.java:833)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB] Caused by: javafx.fxml.LoadException:
[Tue May 23 07:40:30 BST 2023][INFO] [SUB] /com/mascix/swaggerific/main-view.fxml:13
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2722)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2700)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2563)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2531)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.mascix.swaggerific.SwaggerApplication.start(SwaggerApplication.java:22)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at java.security.AccessController.executePrivileged(AccessController.java:169)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at java.security.AccessController.doPrivileged(AccessController.java:399)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Runnable_run_16403f8d32adb631126daa893e5e80085c5d6325(JNIJavaCallWrappers.java:0)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      ... 3 more
[Tue May 23 07:40:30 BST 2023][INFO] [SUB] Caused by: java.lang.RuntimeException: Cannot create instance of javafx.scene.input.KeyCodeCombination with given set of properties: [code, shortcut, meta, shift, alt, control]
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at com.sun.javafx.fxml.builder.ProxyBuilder.build(ProxyBuilder.java:272)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:776)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2969)
[Tue May 23 07:40:30 BST 2023][INFO] [SUB]      at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2654)
```

**Comment by ozkanpakdil** [comment]
fixed
